# Generated by Django 5.2.7 on 2025-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="vehicle_number",
            field=models.CharField(
                blank=True, help_text="Van/Vehicle number", max_length=50
            ),
        ),
    ]
