# Generated by Django 5.2.7 on 2025-11-03 16:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_add_vehicle_number_to_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="auto_allocated",
            field=models.BooleanField(
                default=False,
                help_text="Whether this payment was auto-allocated to sales",
            ),
        ),
        migrations.CreateModel(
            name="CustomerDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Amount to deduct from customer's balance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("return", "Product Return"),
                            ("discount", "Discount/Adjustment"),
                            ("damage", "Damaged Goods"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deductions",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="sales_custo_date_dfd7df_idx"),
                    models.Index(
                        fields=["customer", "date"],
                        name="sales_custo_custome_c1c672_idx",
                    ),
                    models.Index(
                        fields=["-date", "-created_at"],
                        name="sales_custo_date_06fc32_idx",
                    ),
                ],
            },
        ),
    ]
